
name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the project
      uses: actions/checkout@v4
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: Install dependencies
      run: npm install
    - name: Install Playwright
      run: npx playwright install
    - name: Run server
      run: npm run server &
    - name: Run app
      run: npm start
    - name: Run tests
      run: npm test
      
  deploy:
    needs: build_test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
          wait-for-success: true
