name: Build, test and deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Install playwright
      run: npx playwright install
    - name: Run backend service
      run: npm run server &
    - name: Run frontend service
      run: npm start &
    - name: Run tests
      run: npm test
    
    - run: npm run build --if-present
    - run: npm test
